/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.17 at 12:19:00 PM EDT
//

package com.ibm.streams.spl.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for callType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="callType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}expnBase">
 *       &lt;sequence>
 *         &lt;element name="args" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}argsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fcn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "callType",
    propOrder = {"args"})
public class CallType extends ExpnBase {

  @XmlElement(required = true)
  protected ArgsType args;

  @XmlAttribute(name = "fcn", required = true)
  protected String fcn;

  /**
   * Gets the value of the args property.
   *
   * @return possible object is {@link ArgsType }
   */
  public ArgsType getArgs() {
    return args;
  }

  /**
   * Sets the value of the args property.
   *
   * @param value allowed object is {@link ArgsType }
   */
  public void setArgs(ArgsType value) {
    this.args = value;
  }

  /**
   * Gets the value of the fcn property.
   *
   * @return possible object is {@link String }
   */
  public String getFcn() {
    return fcn;
  }

  /**
   * Sets the value of the fcn property.
   *
   * @param value allowed object is {@link String }
   */
  public void setFcn(String value) {
    this.fcn = value;
  }
}
