/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.17 at 12:19:00 PM EDT
//

package com.ibm.streams.spl.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * Java class for descriptionType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="descriptionType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="sampleUri" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="docHref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "descriptionType",
    namespace = "http://www.ibm.com/xmlns/prod/streams/spl/common",
    propOrder = {"value"})
public class DescriptionType {

  @XmlValue protected String value;

  @XmlAttribute(name = "sampleUri")
  protected String sampleUri;

  @XmlAttribute(name = "docHref")
  protected String docHref;

  /**
   * Gets the value of the value property.
   *
   * @return possible object is {@link String }
   */
  public String getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   *
   * @param value allowed object is {@link String }
   */
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * Gets the value of the sampleUri property.
   *
   * @return possible object is {@link String }
   */
  public String getSampleUri() {
    return sampleUri;
  }

  /**
   * Sets the value of the sampleUri property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSampleUri(String value) {
    this.sampleUri = value;
  }

  /**
   * Gets the value of the docHref property.
   *
   * @return possible object is {@link String }
   */
  public String getDocHref() {
    return docHref;
  }

  /**
   * Sets the value of the docHref property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDocHref(String value) {
    this.docHref = value;
  }
}
