/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.17 at 12:19:00 PM EDT
//

package com.ibm.streams.spl.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for expnBase complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="expnBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="cppCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expnBase")
@XmlSeeAlso({
  StreamHistoryType.class,
  CallType.class,
  SubscriptType.class,
  StreamType.class,
  UnaryType.class,
  SymbolType.class,
  EnumType.class,
  AttributeType.class,
  BinaryType.class
})
public class ExpnBase {

  @XmlAttribute(name = "type", required = true)
  protected long type;

  @XmlAttribute(name = "cppCode")
  protected String cppCode;

  /** Gets the value of the type property. */
  public long getType() {
    return type;
  }

  /** Sets the value of the type property. */
  public void setType(long value) {
    this.type = value;
  }

  /**
   * Gets the value of the cppCode property.
   *
   * @return possible object is {@link String }
   */
  public String getCppCode() {
    return cppCode;
  }

  /**
   * Sets the value of the cppCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCppCode(String value) {
    this.cppCode = value;
  }
}
