/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.17 at 12:19:00 PM EDT
//

package com.ibm.streams.spl.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for expressionModeType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p>
 *
 * <pre>
 * &lt;simpleType name="expressionModeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Attribute"/>
 *     &lt;enumeration value="AttributeFree"/>
 *     &lt;enumeration value="Constant"/>
 *     &lt;enumeration value="CustomLiteral"/>
 *     &lt;enumeration value="Expression"/>
 *     &lt;enumeration value="Nonexistent"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "expressionModeType")
@XmlEnum
public enum ExpressionModeType {
  @XmlEnumValue("Attribute")
  ATTRIBUTE("Attribute"),
  @XmlEnumValue("AttributeFree")
  ATTRIBUTE_FREE("AttributeFree"),
  @XmlEnumValue("Constant")
  CONSTANT("Constant"),
  @XmlEnumValue("CustomLiteral")
  CUSTOM_LITERAL("CustomLiteral"),
  @XmlEnumValue("Expression")
  EXPRESSION("Expression"),
  @XmlEnumValue("Nonexistent")
  NONEXISTENT("Nonexistent");
  private final String value;

  ExpressionModeType(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static ExpressionModeType fromValue(String v) {
    for (ExpressionModeType c : ExpressionModeType.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }
}
