/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.17 at 12:19:00 PM EDT
//

package com.ibm.streams.spl.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for expressionType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="expressionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cppType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="splType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hasRuntimeConstant" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="cppExpression" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="splExpression" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hasFunctions" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hasSideEffects" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="readsState" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hasNestedCustomOutputFunction" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hasStreamAttributes" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="parameterExpressionMode" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}expressionModeType" minOccurs="0"/>
 *         &lt;element name="sourceLocation" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}sourceLocationType"/>
 *         &lt;element name="expressionTree" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}expressionTreeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "expressionType",
    propOrder = {
      "cppType",
      "splType",
      "hasRuntimeConstant",
      "cppExpression",
      "splExpression",
      "hasFunctions",
      "hasSideEffects",
      "readsState",
      "hasNestedCustomOutputFunction",
      "hasStreamAttributes",
      "parameterExpressionMode",
      "sourceLocation",
      "expressionTree"
    })
public class ExpressionType {

  @XmlElement(required = true)
  protected String cppType;

  @XmlElement(required = true)
  protected String splType;

  protected boolean hasRuntimeConstant;

  @XmlElement(required = true)
  protected String cppExpression;

  @XmlElement(required = true)
  protected String splExpression;

  protected boolean hasFunctions;
  protected boolean hasSideEffects;
  protected boolean readsState;
  protected Boolean hasNestedCustomOutputFunction;
  protected boolean hasStreamAttributes;

  @XmlSchemaType(name = "string")
  protected ExpressionModeType parameterExpressionMode;

  @XmlElement(required = true)
  protected SourceLocationType sourceLocation;

  protected ExpressionTreeType expressionTree;

  /**
   * Gets the value of the cppType property.
   *
   * @return possible object is {@link String }
   */
  public String getCppType() {
    return cppType;
  }

  /**
   * Sets the value of the cppType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCppType(String value) {
    this.cppType = value;
  }

  /**
   * Gets the value of the splType property.
   *
   * @return possible object is {@link String }
   */
  public String getSplType() {
    return splType;
  }

  /**
   * Sets the value of the splType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSplType(String value) {
    this.splType = value;
  }

  /** Gets the value of the hasRuntimeConstant property. */
  public boolean isHasRuntimeConstant() {
    return hasRuntimeConstant;
  }

  /** Sets the value of the hasRuntimeConstant property. */
  public void setHasRuntimeConstant(boolean value) {
    this.hasRuntimeConstant = value;
  }

  /**
   * Gets the value of the cppExpression property.
   *
   * @return possible object is {@link String }
   */
  public String getCppExpression() {
    return cppExpression;
  }

  /**
   * Sets the value of the cppExpression property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCppExpression(String value) {
    this.cppExpression = value;
  }

  /**
   * Gets the value of the splExpression property.
   *
   * @return possible object is {@link String }
   */
  public String getSplExpression() {
    return splExpression;
  }

  /**
   * Sets the value of the splExpression property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSplExpression(String value) {
    this.splExpression = value;
  }

  /** Gets the value of the hasFunctions property. */
  public boolean isHasFunctions() {
    return hasFunctions;
  }

  /** Sets the value of the hasFunctions property. */
  public void setHasFunctions(boolean value) {
    this.hasFunctions = value;
  }

  /** Gets the value of the hasSideEffects property. */
  public boolean isHasSideEffects() {
    return hasSideEffects;
  }

  /** Sets the value of the hasSideEffects property. */
  public void setHasSideEffects(boolean value) {
    this.hasSideEffects = value;
  }

  /** Gets the value of the readsState property. */
  public boolean isReadsState() {
    return readsState;
  }

  /** Sets the value of the readsState property. */
  public void setReadsState(boolean value) {
    this.readsState = value;
  }

  /**
   * Gets the value of the hasNestedCustomOutputFunction property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isHasNestedCustomOutputFunction() {
    return hasNestedCustomOutputFunction;
  }

  /**
   * Sets the value of the hasNestedCustomOutputFunction property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setHasNestedCustomOutputFunction(Boolean value) {
    this.hasNestedCustomOutputFunction = value;
  }

  /** Gets the value of the hasStreamAttributes property. */
  public boolean isHasStreamAttributes() {
    return hasStreamAttributes;
  }

  /** Sets the value of the hasStreamAttributes property. */
  public void setHasStreamAttributes(boolean value) {
    this.hasStreamAttributes = value;
  }

  /**
   * Gets the value of the parameterExpressionMode property.
   *
   * @return possible object is {@link ExpressionModeType }
   */
  public ExpressionModeType getParameterExpressionMode() {
    return parameterExpressionMode;
  }

  /**
   * Sets the value of the parameterExpressionMode property.
   *
   * @param value allowed object is {@link ExpressionModeType }
   */
  public void setParameterExpressionMode(ExpressionModeType value) {
    this.parameterExpressionMode = value;
  }

  /**
   * Gets the value of the sourceLocation property.
   *
   * @return possible object is {@link SourceLocationType }
   */
  public SourceLocationType getSourceLocation() {
    return sourceLocation;
  }

  /**
   * Sets the value of the sourceLocation property.
   *
   * @param value allowed object is {@link SourceLocationType }
   */
  public void setSourceLocation(SourceLocationType value) {
    this.sourceLocation = value;
  }

  /**
   * Gets the value of the expressionTree property.
   *
   * @return possible object is {@link ExpressionTreeType }
   */
  public ExpressionTreeType getExpressionTree() {
    return expressionTree;
  }

  /**
   * Sets the value of the expressionTree property.
   *
   * @param value allowed object is {@link ExpressionTreeType }
   */
  public void setExpressionTree(ExpressionTreeType value) {
    this.expressionTree = value;
  }
}
