/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.17 at 12:19:00 PM EDT
//

package com.ibm.streams.spl.model;

import com.ibm.streams.spl.model.tupletype.TupleType;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for inputPortType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="inputPortType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}portType">
 *       &lt;sequence>
 *         &lt;element name="history" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="window" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}windowType" minOccurs="0"/>
 *         &lt;element name="tupleLogic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="punctLogic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="attributes" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}inputAttributesType"/>
 *         &lt;element name="tuple" type="{http://www.ibm.com/xmlns/prod/streams/spl/tupleType}tupleType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isControlPort" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "inputPortType",
    propOrder = {"history", "window", "tupleLogic", "punctLogic", "attributes", "tuple"})
public class InputPortType extends PortType {

  protected BigInteger history;
  protected WindowType window;
  protected String tupleLogic;
  protected String punctLogic;

  @XmlElement(required = true)
  protected InputAttributesType attributes;

  @XmlElement(required = true)
  protected TupleType tuple;

  @XmlAttribute(name = "isControlPort")
  protected Boolean isControlPort;

  /**
   * Gets the value of the history property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getHistory() {
    return history;
  }

  /**
   * Sets the value of the history property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setHistory(BigInteger value) {
    this.history = value;
  }

  /**
   * Gets the value of the window property.
   *
   * @return possible object is {@link WindowType }
   */
  public WindowType getWindow() {
    return window;
  }

  /**
   * Sets the value of the window property.
   *
   * @param value allowed object is {@link WindowType }
   */
  public void setWindow(WindowType value) {
    this.window = value;
  }

  /**
   * Gets the value of the tupleLogic property.
   *
   * @return possible object is {@link String }
   */
  public String getTupleLogic() {
    return tupleLogic;
  }

  /**
   * Sets the value of the tupleLogic property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTupleLogic(String value) {
    this.tupleLogic = value;
  }

  /**
   * Gets the value of the punctLogic property.
   *
   * @return possible object is {@link String }
   */
  public String getPunctLogic() {
    return punctLogic;
  }

  /**
   * Sets the value of the punctLogic property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPunctLogic(String value) {
    this.punctLogic = value;
  }

  /**
   * Gets the value of the attributes property.
   *
   * @return possible object is {@link InputAttributesType }
   */
  public InputAttributesType getAttributes() {
    return attributes;
  }

  /**
   * Sets the value of the attributes property.
   *
   * @param value allowed object is {@link InputAttributesType }
   */
  public void setAttributes(InputAttributesType value) {
    this.attributes = value;
  }

  /**
   * Gets the value of the tuple property.
   *
   * @return possible object is {@link TupleType }
   */
  public TupleType getTuple() {
    return tuple;
  }

  /**
   * Sets the value of the tuple property.
   *
   * @param value allowed object is {@link TupleType }
   */
  public void setTuple(TupleType value) {
    this.tuple = value;
  }

  /**
   * Gets the value of the isControlPort property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isIsControlPort() {
    return isControlPort;
  }

  /**
   * Sets the value of the isControlPort property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setIsControlPort(Boolean value) {
    this.isControlPort = value;
  }
}
