/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.17 at 12:19:00 PM EDT
//

package com.ibm.streams.spl.model;

import com.ibm.streams.spl.model.tupletype.TupleType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for outputPortType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="outputPortType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}portType">
 *       &lt;sequence>
 *         &lt;element name="attributes" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}outputAttributesType"/>
 *         &lt;element name="tuple" type="{http://www.ibm.com/xmlns/prod/streams/spl/tupleType}tupleType"/>
 *         &lt;element name="finalPunctuationPortScope" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}portScopeType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "outputPortType",
    propOrder = {"attributes", "tuple", "finalPunctuationPortScope"})
public class OutputPortType extends PortType {

  @XmlElement(required = true)
  protected OutputAttributesType attributes;

  @XmlElement(required = true)
  protected TupleType tuple;

  @XmlElement(required = true)
  protected PortScopeType finalPunctuationPortScope;

  /**
   * Gets the value of the attributes property.
   *
   * @return possible object is {@link OutputAttributesType }
   */
  public OutputAttributesType getAttributes() {
    return attributes;
  }

  /**
   * Sets the value of the attributes property.
   *
   * @param value allowed object is {@link OutputAttributesType }
   */
  public void setAttributes(OutputAttributesType value) {
    this.attributes = value;
  }

  /**
   * Gets the value of the tuple property.
   *
   * @return possible object is {@link TupleType }
   */
  public TupleType getTuple() {
    return tuple;
  }

  /**
   * Sets the value of the tuple property.
   *
   * @param value allowed object is {@link TupleType }
   */
  public void setTuple(TupleType value) {
    this.tuple = value;
  }

  /**
   * Gets the value of the finalPunctuationPortScope property.
   *
   * @return possible object is {@link PortScopeType }
   */
  public PortScopeType getFinalPunctuationPortScope() {
    return finalPunctuationPortScope;
  }

  /**
   * Sets the value of the finalPunctuationPortScope property.
   *
   * @param value allowed object is {@link PortScopeType }
   */
  public void setFinalPunctuationPortScope(PortScopeType value) {
    this.finalPunctuationPortScope = value;
  }
}
