/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.17 at 12:19:00 PM EDT
//

package com.ibm.streams.spl.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for outputAttributeType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="outputAttributeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}inputAttributeType">
 *       &lt;sequence>
 *         &lt;element name="assignment" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}assignmentType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "outputAttributeType",
    propOrder = {"assignment"})
public class OutputAttributeType extends InputAttributeType {

  protected AssignmentType assignment;

  /**
   * Gets the value of the assignment property.
   *
   * @return possible object is {@link AssignmentType }
   */
  public AssignmentType getAssignment() {
    return assignment;
  }

  /**
   * Sets the value of the assignment property.
   *
   * @param value allowed object is {@link AssignmentType }
   */
  public void setAssignment(AssignmentType value) {
    this.assignment = value;
  }
}
