/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.17 at 12:19:00 PM EDT
//

package com.ibm.streams.spl.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for portType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="portType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tupleCppName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tupleCppType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tupleSPLType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="facade" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="mutationAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="sourceLocation" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}sourceLocationType"/>
 *         &lt;element name="annotations" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}annotationsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "portType",
    propOrder = {
      "index",
      "tupleCppName",
      "tupleCppType",
      "tupleSPLType",
      "facade",
      "mutationAllowed",
      "sourceLocation",
      "annotations"
    })
@XmlSeeAlso({OutputPortType.class, InputPortType.class})
public class PortType {

  @XmlElement(required = true)
  protected BigInteger index;

  @XmlElement(required = true)
  protected String tupleCppName;

  @XmlElement(required = true)
  protected String tupleCppType;

  @XmlElement(required = true)
  protected String tupleSPLType;

  protected boolean facade;
  protected boolean mutationAllowed;

  @XmlElement(required = true)
  protected SourceLocationType sourceLocation;

  protected AnnotationsType annotations;

  /**
   * Gets the value of the index property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getIndex() {
    return index;
  }

  /**
   * Sets the value of the index property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setIndex(BigInteger value) {
    this.index = value;
  }

  /**
   * Gets the value of the tupleCppName property.
   *
   * @return possible object is {@link String }
   */
  public String getTupleCppName() {
    return tupleCppName;
  }

  /**
   * Sets the value of the tupleCppName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTupleCppName(String value) {
    this.tupleCppName = value;
  }

  /**
   * Gets the value of the tupleCppType property.
   *
   * @return possible object is {@link String }
   */
  public String getTupleCppType() {
    return tupleCppType;
  }

  /**
   * Sets the value of the tupleCppType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTupleCppType(String value) {
    this.tupleCppType = value;
  }

  /**
   * Gets the value of the tupleSPLType property.
   *
   * @return possible object is {@link String }
   */
  public String getTupleSPLType() {
    return tupleSPLType;
  }

  /**
   * Sets the value of the tupleSPLType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTupleSPLType(String value) {
    this.tupleSPLType = value;
  }

  /** Gets the value of the facade property. */
  public boolean isFacade() {
    return facade;
  }

  /** Sets the value of the facade property. */
  public void setFacade(boolean value) {
    this.facade = value;
  }

  /** Gets the value of the mutationAllowed property. */
  public boolean isMutationAllowed() {
    return mutationAllowed;
  }

  /** Sets the value of the mutationAllowed property. */
  public void setMutationAllowed(boolean value) {
    this.mutationAllowed = value;
  }

  /**
   * Gets the value of the sourceLocation property.
   *
   * @return possible object is {@link SourceLocationType }
   */
  public SourceLocationType getSourceLocation() {
    return sourceLocation;
  }

  /**
   * Sets the value of the sourceLocation property.
   *
   * @param value allowed object is {@link SourceLocationType }
   */
  public void setSourceLocation(SourceLocationType value) {
    this.sourceLocation = value;
  }

  /**
   * Gets the value of the annotations property.
   *
   * @return possible object is {@link AnnotationsType }
   */
  public AnnotationsType getAnnotations() {
    return annotations;
  }

  /**
   * Sets the value of the annotations property.
   *
   * @param value allowed object is {@link AnnotationsType }
   */
  public void setAnnotations(AnnotationsType value) {
    this.annotations = value;
  }
}
