/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.17 at 12:19:00 PM EDT
//

package com.ibm.streams.spl.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for toolkitType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="toolkitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rootDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isCurrentToolkit" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "toolkitType",
    propOrder = {"name", "rootDirectory", "index"})
public class ToolkitType {

  @XmlElement(required = true)
  protected String name;

  @XmlElement(required = true)
  protected String rootDirectory;

  protected long index;

  @XmlAttribute(name = "isCurrentToolkit", required = true)
  protected boolean isCurrentToolkit;

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the rootDirectory property.
   *
   * @return possible object is {@link String }
   */
  public String getRootDirectory() {
    return rootDirectory;
  }

  /**
   * Sets the value of the rootDirectory property.
   *
   * @param value allowed object is {@link String }
   */
  public void setRootDirectory(String value) {
    this.rootDirectory = value;
  }

  /** Gets the value of the index property. */
  public long getIndex() {
    return index;
  }

  /** Sets the value of the index property. */
  public void setIndex(long value) {
    this.index = value;
  }

  /** Gets the value of the isCurrentToolkit property. */
  public boolean isIsCurrentToolkit() {
    return isCurrentToolkit;
  }

  /** Sets the value of the isCurrentToolkit property. */
  public void setIsCurrentToolkit(boolean value) {
    this.isCurrentToolkit = value;
  }
}
