/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.17 at 12:19:00 PM EDT
//

package com.ibm.streams.spl.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for windowType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="windowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="partitioned" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="partitionEviction" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}partitionEvictionType" minOccurs="0"/>
 *         &lt;element name="evictionPolicy" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}windowPolicyType"/>
 *         &lt;element name="triggerPolicy" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}windowPolicyType" minOccurs="0"/>
 *         &lt;element name="sourceLocation" type="{http://www.ibm.com/xmlns/prod/streams/spl/operator/instance}sourceLocationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "windowType",
    propOrder = {
      "partitioned",
      "partitionEviction",
      "evictionPolicy",
      "triggerPolicy",
      "sourceLocation"
    })
public class WindowType {

  protected boolean partitioned;
  protected PartitionEvictionType partitionEviction;

  @XmlElement(required = true)
  protected WindowPolicyType evictionPolicy;

  protected WindowPolicyType triggerPolicy;

  @XmlElement(required = true)
  protected SourceLocationType sourceLocation;

  /** Gets the value of the partitioned property. */
  public boolean isPartitioned() {
    return partitioned;
  }

  /** Sets the value of the partitioned property. */
  public void setPartitioned(boolean value) {
    this.partitioned = value;
  }

  /**
   * Gets the value of the partitionEviction property.
   *
   * @return possible object is {@link PartitionEvictionType }
   */
  public PartitionEvictionType getPartitionEviction() {
    return partitionEviction;
  }

  /**
   * Sets the value of the partitionEviction property.
   *
   * @param value allowed object is {@link PartitionEvictionType }
   */
  public void setPartitionEviction(PartitionEvictionType value) {
    this.partitionEviction = value;
  }

  /**
   * Gets the value of the evictionPolicy property.
   *
   * @return possible object is {@link WindowPolicyType }
   */
  public WindowPolicyType getEvictionPolicy() {
    return evictionPolicy;
  }

  /**
   * Sets the value of the evictionPolicy property.
   *
   * @param value allowed object is {@link WindowPolicyType }
   */
  public void setEvictionPolicy(WindowPolicyType value) {
    this.evictionPolicy = value;
  }

  /**
   * Gets the value of the triggerPolicy property.
   *
   * @return possible object is {@link WindowPolicyType }
   */
  public WindowPolicyType getTriggerPolicy() {
    return triggerPolicy;
  }

  /**
   * Sets the value of the triggerPolicy property.
   *
   * @param value allowed object is {@link WindowPolicyType }
   */
  public void setTriggerPolicy(WindowPolicyType value) {
    this.triggerPolicy = value;
  }

  /**
   * Gets the value of the sourceLocation property.
   *
   * @return possible object is {@link SourceLocationType }
   */
  public SourceLocationType getSourceLocation() {
    return sourceLocation;
  }

  /**
   * Sets the value of the sourceLocation property.
   *
   * @param value allowed object is {@link SourceLocationType }
   */
  public void setSourceLocation(SourceLocationType value) {
    this.sourceLocation = value;
  }
}
