#!/bin/sh

#
# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Argument check
#
if [ $# -ne 3 ]; then
  echo "Usage: $0 HOST PORT SAB_FILE"
  exit 1
fi

# Extract the key value
#
KEY=$(basename $3)

# Call upon redis
#
redis-cli -h $1 -p $2 -x HSET apps ${KEY} <$3
