/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.17 at 12:18:58 PM EDT
//

package com.ibm.streams.spl.model.tupletype;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for mapType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="mapType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="key" type="{http://www.ibm.com/xmlns/prod/streams/spl/tupleType}typeType" minOccurs="0"/>
 *         &lt;element name="value" type="{http://www.ibm.com/xmlns/prod/streams/spl/tupleType}typeType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="bound" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="keyType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valueType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "mapType",
    propOrder = {"key", "value"})
public class MapType {

  protected TypeType key;
  protected TypeType value;

  @XmlAttribute(name = "bound")
  protected Long bound;

  @XmlAttribute(name = "keyType")
  protected String keyType;

  @XmlAttribute(name = "valueType")
  protected String valueType;

  /**
   * Gets the value of the key property.
   *
   * @return possible object is {@link TypeType }
   */
  public TypeType getKey() {
    return key;
  }

  /**
   * Sets the value of the key property.
   *
   * @param value allowed object is {@link TypeType }
   */
  public void setKey(TypeType value) {
    this.key = value;
  }

  /**
   * Gets the value of the value property.
   *
   * @return possible object is {@link TypeType }
   */
  public TypeType getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   *
   * @param value allowed object is {@link TypeType }
   */
  public void setValue(TypeType value) {
    this.value = value;
  }

  /**
   * Gets the value of the bound property.
   *
   * @return possible object is {@link Long }
   */
  public Long getBound() {
    return bound;
  }

  /**
   * Sets the value of the bound property.
   *
   * @param value allowed object is {@link Long }
   */
  public void setBound(Long value) {
    this.bound = value;
  }

  /**
   * Gets the value of the keyType property.
   *
   * @return possible object is {@link String }
   */
  public String getKeyType() {
    return keyType;
  }

  /**
   * Sets the value of the keyType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setKeyType(String value) {
    this.keyType = value;
  }

  /**
   * Gets the value of the valueType property.
   *
   * @return possible object is {@link String }
   */
  public String getValueType() {
    return valueType;
  }

  /**
   * Sets the value of the valueType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setValueType(String value) {
    this.valueType = value;
  }
}
