#!/bin/sh

#
# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -xe

# Fetch the SAB from the repository
#
REPOSITORY_URL=streams-api.${STREAMS_INSTANCE_ID}
FETCHED=0

for i in `seq 0 29`
do
    redis-cli -h ${REPOSITORY_URL} --raw HGET apps ${STREAMS_SAB_NAME} > /tmp/${STREAMS_SAB_NAME}
    if [ $? = 0 ]
    then
        FETCHED=1
        break
    fi
    sleep 1
done

if [ ${FETCHED} = 0 ]
then
    echo "Cannot reach redis, aborting"
    exit 1
fi

# Unpack the SAB
#
mkdir /tmp/assets && cd /tmp/assets
${JAVA_HOME}/bin/jar -xf /tmp/${STREAMS_SAB_NAME}

# Unpack the bundle
#
tar -C /tmp/assets -xf /tmp/assets/tar/bundle.tar

# Define the valgrind command if requests
#
if [ ${STREAMS_PE_USE_VALGRIND} = "true" ]
then
    CMD_WRAPPER="/usr/bin/valgrind --leak-check=full --num-callers=64 --show-leak-kinds=all --track-origins=yes"
fi

# Run the PE
#
exec ${CMD_WRAPPER} /usr/local/streams/system/impl/bin/streams-k8s-pe
