/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_streams_spl_internal_api_port_SubsExpressionEvalJNI */

#ifndef _Included_com_ibm_streams_spl_internal_api_port_SubsExpressionEvalJNI
#define _Included_com_ibm_streams_spl_internal_api_port_SubsExpressionEvalJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_streams_spl_internal_api_port_SubsExpressionEvalJNI
 * Method:    initCpp
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_ibm_streams_spl_internal_api_port_SubsExpressionEvalJNI_initCpp(JNIEnv*, jobject);

/*
 * Class:     com_ibm_streams_spl_internal_api_port_SubsExpressionEvalJNI
 * Method:    closeCpp
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_ibm_streams_spl_internal_api_port_SubsExpressionEvalJNI_closeCpp(JNIEnv*, jobject);

/*
 * Class:     com_ibm_streams_spl_internal_api_port_SubsExpressionEvalJNI
 * Method:    evaluateCpp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_ibm_streams_spl_internal_api_port_SubsExpressionEvalJNI_evaluateCpp(JNIEnv*,
                                                                             jobject,
                                                                             jstring,
                                                                             jstring);

#ifdef __cplusplus
}
#endif
#endif
