/*
 * Copyright 2021 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_streams_spl_internal_api_port_LogicalToPhysicalJNI */

#ifndef _Included_com_ibm_streams_spl_internal_api_port_LogicalToPhysicalJNI
#define _Included_com_ibm_streams_spl_internal_api_port_LogicalToPhysicalJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_streams_spl_internal_api_port_LogicalToPhysicalJNI
 * Method:    submissionTimeExpressionEvalCpp
 * Signature: (Ljava/lang/String;JJLjava/lang/StringBuffer;)Ljava/lang/String;
 */
__attribute__((visibility("default"))) JNIEXPORT jstring JNICALL
Java_com_ibm_streams_spl_internal_api_port_LogicalToPhysicalJNI_submissionTimeExpressionEvalCpp(
  JNIEnv*,
  jobject,
  jstring,
  jlong,
  jlong,
  jobject);

/*
 * Class:     com_ibm_streams_spl_internal_api_port_LogicalToPhysicalJNI
 * Method:    submissionTimePropertiesEvalCpp
 * Signature: (Ljava/lang/String;JJLjava/lang/StringBuffer;)Ljava/lang/String;
 */
__attribute__((visibility("default"))) JNIEXPORT jstring JNICALL
Java_com_ibm_streams_spl_internal_api_port_LogicalToPhysicalJNI_submissionTimePropertiesEvalCpp(
  JNIEnv*,
  jobject,
  jstring,
  jlong,
  jlong,
  jobject);

/*
 * Class:     com_ibm_streams_spl_internal_api_port_LogicalToPhysicalJNI
 * Method:    transformCpp
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
__attribute__((visibility("default"))) JNIEXPORT jstring JNICALL
Java_com_ibm_streams_spl_internal_api_port_LogicalToPhysicalJNI_transformCpp(JNIEnv*,
                                                                             jobject,
                                                                             jstring,
                                                                             jobject);

#ifdef __cplusplus
}
#endif
#endif
