#!/usr/bin/perl

#
# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

use strict;
use warnings;
use FindBin;
use lib "${FindBin::Bin}";
use lib "${FindBin::Bin}/../system/impl/bin";
use SPL::Helper;
use SPL::Msg; # load message constants

sub escape($);

my $binDir = ${FindBin::Bin};
my $java = $ENV{JAVA_HOME} . "/bin/java";
my $splAppInfoJar = $binDir . "/../system/impl/lib/com.ibm.streams.spl-app-info.jar";
my $classPath = "-classpath $splAppInfoJar";

my $options = "";
while (scalar @ARGV > 0) {
    my $arg = shift;
    $arg = escape($arg);
    $options .= " $arg";
}

my $cmd = "$java $classPath com.ibm.streams.splappinfo.core.Main $options";
my $rc = system($cmd);
$rc = $rc >> 8;
exit($rc);

sub escape($)
{
    my ($str) = @_;
    $str =~ s/(['"])/\\$1/g;
    return $str;
}
