#!/bin/sh

#
# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

OBJDIR=$1
CPPSTD=$2

shift
shift

/usr/bin/clang-tidy                                 \
  -fix                                              \
  -checks="-*,readability-braces-around-statements" \
  -p="${OBJDIR}"                                    \
  -format-style=file                                \
  -extra-arg-before="-std=${CPPSTD}"                \
  -extra-arg-before="-isystem/opt/clang/include"    \
  $@
