#!/bin/sh

#
# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

fail() {

    echo $* >&2
    exit 1

}

# First argument is the pkgconfig directory
pkg_config_dir=$1
shift;

test -n "$*" || echo "install-pkg-config.sh: Nothing to install"

while test ! -z "$1" ; do

    test -f "$1" || fail "Not a file: $1"

    src=$1
    dst=`basename $1`
    dst=$pkg_config_dir/${dst%.tmpl}

    test -d $pkg_config_dir || mkdir -p $pkg_config_dir
#    sed -e "s![@%]prefix[@%]!$prefix!g" -e "s![@%]dstprefix[@%]!$prefix!g" \
#        -e "s![@%]prefix_install[@%]!$prefix_install!g" -e "s![@%]dstprefix_install[@%]!$prefix_install!g" \
#        -e "s![@%]prefix_noship[@%]!$prefix_noship!g" -e "s![@%]dstprefix_noship[@%]!$prefix_noship!g" $src > $dst
    cp -f $src $dst

    shift

done
