#!/bin/sh

#
# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -ne 2 ]; then
    echo "Usage: $0 INSTALL_PATH VERSION";
    exit 1;
fi

INSTALL_PATH=$1
VERSION=$2

function process
{
    OLD_PWD=$PWD;
    cd ${INSTALL_PATH}/$1;
    #
    for file in com.ibm.streams.*.jar; do
        [ -h  $file ] && rm -f $file
    done
    #
    for file in streams.*${VERSION}.jar; do
        TARGET=com.ibm.$(echo $file | sed "s/-${VERSION}//g");
        ln -s $file ${TARGET};
    done
    #
    cd ${OLD_PWD};
}

process lib
process system/impl/lib
