#!/bin/bash

#
# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

TMP_FILE=`mktemp /tmp/doxyfilter.XXXX.pm`
trap "{ rm -f $TMP_FILE; }" INT TERM EXIT;
cat $1 | awk 'BEGIN{ins=0;}/^# *DOXYGEN_SKIP_FOR_USERS/{ins=1;} /^# *END_DOXYGEN_SKIP_FOR_USERS/{ins=0;} {if(ins==0)print;}' > $TMP_FILE
doxygenfilter $TMP_FILE
exit;
